### ISSUE TITLE
Auditbeat学习笔记

### ISSUE THREAD

**Issue by woshikid** [woshikid/blog#112]
# 安装/启动
```shell
curl -L -O https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-7.4.2-linux-x86_64.tar.gz
tar xzvf auditbeat-7.4.2-linux-x86_64.tar.gz
cd auditbeat-7.4.2-linux-x86_64
sudo chown root auditbeat.yml
sudo ./auditbeat -e
```

# 配置
vi auditbeat.yml
```yml
- module: auditd
  audit_rules: |
    -a always,exit -F arch=b32 -S all -F key=32bit-abi
    -w /etc/group -p wa -k identity
    -w /etc/passwd -p wa -k identity
    -w /etc/gshadow -p wa -k identity
    -a always,exit -F arch=b64 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EACCES -k access
    -a always,exit -F arch=b64 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EPERM -k access

- module: file_integrity
  paths:
  - /bin
  - /usr/bin
  - /sbin
  - /usr/sbin
  - /etc

- module: system
  datasets:
    - host    # General host information, e.g. uptime, IPs
    - login   # User logins, logouts, and system boots.
    - package # Installed, updated, and removed packages
    - process # Started and stopped processes
    - socket  # Opened and closed sockets
    - user    # User information

output.elasticsearch:
  hosts: ["myEShost:9200"]
  #username: "elastic"
  #password: "elastic"

output.logstash:
  hosts: ["mylogstashhost1:5044", "mylogstashhost2:5044"]
  loadbalance: true

setup.kibana:
  host: "mykibanahost:5601"
```

## 手工加载index template
```shell
./auditbeat setup --index-management -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["localhost:9200"]'
```

## 加载Kibana dashboards
```shell
./auditbeat setup --dashboards
```

# 关闭系统审计工具
```shell
sudo service auditd status
sudo service auditd stop
sudo chkconfig auditd off
sudo systemctl mask systemd-journald-audit.socket
```

# 查看内核审计状态
```shell
sudo ./auditbeat show auditd-rules
sudo ./auditbeat show auditd-status
```
