### ISSUE TITLE
DBCP基本配置

### ISSUE THREAD

**Issue by woshikid** [woshikid/blog#148]
# DBCP
## POM
```xml
<dependency>
	<groupId>commons-dbcp</groupId>
	<artifactId>commons-dbcp</artifactId>
	<version>1.4</version>
</dependency>
```

## 配置bean
```xml
<bean id="dataSource" class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
    <property name="driverClassName" value="com.mysql.cj.jdbc.Driver" />
    <property name="url" value="jdbc:mysql://127.0.0.1:3306/test" />
    <property name="username" value="test" />
    <property name="password" value="test" />
    <!-- 初始连接数，默认为0 -->
    <property name="initialSize" value="1" />
    <!-- 最小空闲数，默认为0 -->
    <property name="minIdle" value="1" />
    <!-- 最大空闲数，超过会立即销毁，默认为8 -->
    <property name="maxIdle" value="100" />
    <!-- 最大连接数，默认为8 -->
    <property name="maxActive" value="100" />
    <!-- 获取连接最大等待毫秒，默认为-1 -->
    <property name="maxWait" value="10000" />
    <!-- 连接测试sql，默认为空 -->
    <property name="validationQuery" value="select 1" />
    <!-- 获取连接时测试，默认为true -->
    <property name="testOnBorrow" value="false" />
    <!-- 归还连接时测试，默认为false -->
    <property name="testOnReturn" value="false" />
    <!-- 空闲时测试连接，默认为false -->
    <property name="testWhileIdle" value="true" />
    <!-- 连接驱逐线程运行间隔，默认为-1 -->
    <property name="timeBetweenEvictionRunsMillis" value="60000" />
    <!-- 连接保持空闲而不被驱逐的最小时间，默认为1800秒 -->
    <property name="minEvictableIdleTimeMillis" value="1800000" />
    <!-- 连接泄漏强制回收，默认为false -->
    <property name="removeAbandoned" value="true" />
    <!-- 连接泄漏超时时间，默认为300秒 -->
    <property name="removeAbandonedTimeout" value="1800" />
    <!-- 强制回收连接时记录日志，默认为false -->
    <property name="logAbandoned" value="true" />
</bean>
```

# DBCP2
## POM
```xml
<dependency>
	<groupId>org.apache.commons</groupId>
	<artifactId>commons-dbcp2</artifactId>
	<version>2.8.0</version>
</dependency>
```

## 配置bean
```xml
<bean id="dataSource" class="org.apache.commons.dbcp2.BasicDataSource" destroy-method="close">
    <property name="driverClassName" value="com.mysql.cj.jdbc.Driver" />
    <property name="url" value="jdbc:mysql://127.0.0.1:3306/test" />
    <property name="username" value="test" />
    <property name="password" value="test" />
    <!-- 初始连接数，默认为0 -->
    <property name="initialSize" value="1" />
    <!-- 最小空闲数，默认为0 -->
    <property name="minIdle" value="1" />
    <!-- 最大空闲数，超过会立即销毁，默认为8 -->
    <property name="maxIdle" value="100" />
    <!-- 最大连接数，默认为8 -->
    <property name="maxTotal" value="100" />
    <!-- 获取连接最大等待毫秒，默认为-1 -->
    <property name="maxWaitMillis" value="10000" />
    <!-- 连接测试sql，默认为空 -->
    <property name="validationQuery" value="select 1" />
    <!-- 获取连接时测试，默认为true -->
    <property name="testOnBorrow" value="false" />
    <!-- 归还连接时测试，默认为false -->
    <property name="testOnReturn" value="false" />
    <!-- 空闲时测试连接，默认为false -->
    <property name="testWhileIdle" value="true" />
    <!-- 连接驱逐线程运行间隔，默认为-1 -->
    <property name="timeBetweenEvictionRunsMillis" value="60000" />
    <!-- 连接保持空闲而不被驱逐的最小时间，默认为1800秒 -->
    <property name="minEvictableIdleTimeMillis" value="1800000" />
    <!-- 获取连接时回收泄漏连接，默认为false -->
    <property name="removeAbandonedOnBorrow" value="false" />
    <!-- 空闲时回收泄漏连接，默认为false -->
    <property name="removeAbandonedOnMaintenance" value="true" />
    <!-- 连接泄漏超时时间，默认为300秒 -->
    <property name="removeAbandonedTimeout" value="1800" />
    <!-- 强制回收连接时记录日志，默认为false -->
    <property name="logAbandoned" value="true" />
</bean>
```

## 配置JNDI
```xml
<Resource name="jdbc/TestDB" auth="Container" type="javax.sql.DataSource"
    driverClassName="com.mysql.cj.jdbc.Driver"
    url="jdbc:mysql://127.0.0.1:3306/test" username="test" password="test"
    initialSize="1" minIdle="1" maxIdle="100" maxTotal="100" maxWaitMillis="10000" validationQuery="select 1"
    testOnBorrow="false" testWhileIdle="true" timeBetweenEvictionRunsMillis="60000"
    removeAbandonedOnMaintenance="true" removeAbandonedTimeout="1800" logAbandoned="true" />
```

## Spring Boot
指定数据源类型
```yml
spring.datasource.type: org.apache.commons.dbcp2.BasicDataSource
```

默认配置
```yml
spring.datasource.dbcp2:
  connection-init-sqls: "" # 连接初始化sql
  initial-size: 0 # 初始连接数
  min-idle: 0 # 最小空闲数
  max-idle: 8 # 最大空闲数
  max-total: 8 # 最大连接数
  max-wait-millis: -1 # 获取连接最大等待毫秒
  max-conn-lifetime-millis: -1 # 最大存活时间
  validation-query: "" # 连接测试sql
  validation-query-timeout: -1 # 连接测试超时时间
  test-on-create: false # 建立连接时测试
  test-on-borrow: true # 获取连接时测试
  test-on-return: false # 归还连接时测试
  test-while-idle: false # 空闲时测试连接
  time-between-eviction-runs-millis: -1 # 连接驱逐线程运行间隔
  min-evictable-idle-time-millis: 1800000 # 连接保持空闲而不被驱逐的最小时间
  remove-abandoned-on-borrow: false # 获取连接时回收泄漏连接
  remove-abandoned-on-maintenance: false # 空闲时回收泄漏连接
  remove-abandoned-timeout: 300 # 连接泄漏超时时间
  log-abandoned: false # 强制回收连接时记录日志
```
