### ISSUE TITLE
Spring JDBC学习笔记

### ISSUE THREAD

**Issue by woshikid** [woshikid/blog#150]
# JDBC
POM
```xml
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-jdbc</artifactId>
    <version>5.2.8.RELEASE</version>
</dependency>
```

配置数据源
```xml
<bean id="dataSource" class="org.springframework.jdbc.datasource.DriverManagerDataSource">
    <property name="driverClassName" value="com.mysql.cj.jdbc.Driver" />
    <property name="url" value="jdbc:mysql://127.0.0.1:3306/test" />
    <property name="username" value="test" />
    <property name="password" value="test" />
</bean>
```
或使用Java配置
```java
@Bean("dataSource")
public DataSource driverManagerDataSource() throws ClassNotFoundException {
    Class.forName("com.mysql.cj.jdbc.Driver");
    return new DriverManagerDataSource("jdbc:mysql://127.0.0.1:3306/test", "test", "test");
    //return new SimpleDriverDataSource(new com.mysql.cj.jdbc.Driver(), "jdbc:mysql://127.0.0.1:3306/test", "test", "test");
    //return new SingleConnectionDataSource("jdbc:mysql://127.0.0.1:3306/test", "test", "test", true);
}
```

Mapper
```java
public class UserMapper implements RowMapper<User> {

    @Override
    public User mapRow(ResultSet rs, int rowNum) throws SQLException {
        User user = new User();
        user.setId(rs.getInt("id"));
        user.setName(rs.getString("name"));
        user.setAge(rs.getInt("age"));
        return user;
    }

}
```
或使用`BeanPropertyRowMapper.newInstance(User.class)`自动生成

JdbcTemplate
```xml
<bean id="jdbcTemplate" class="org.springframework.jdbc.core.JdbcTemplate">
    <property name="dataSource" ref="dataSource" />
</bean>

<bean id="namedJdbcTemplate" class="org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate">
    <constructor-arg ref="dataSource" />
</bean>
```
或使用Java配置
```java
@Bean
public JdbcTemplate jdbcTemplate(DataSource dataSource) {
    return new JdbcTemplate(dataSource);
}

@Bean
public NamedParameterJdbcTemplate namedJdbcTemplate(DataSource dataSource) {
    return new NamedParameterJdbcTemplate(dataSource);
}
```

DAO
```java
@Repository
public class UserDao {

    @Autowired
    private JdbcTemplate jdbcTemplate;
    
    @Autowired
    private NamedParameterJdbcTemplate namedJdbcTemplate;
    
    //private RowMapper<User> userMapper = new UserMapper();
    private RowMapper<User> userMapper = BeanPropertyRowMapper.newInstance(User.class);
    
    public int add(User user) {
        SqlParameterSource source = new BeanPropertySqlParameterSource(user);
        return namedJdbcTemplate.update("insert into user(name, age) values(:name, :age)", source);
    }
    
    public int add(Map<String, ?> map) {
        return namedJdbcTemplate.update("insert into user(name, age) values(:name, :age)", map);
    }
    
    public int add(String name, int age) {
        return jdbcTemplate.update("insert into user(name, age) values(?, ?)", name, age);
    }
    
    public int[] addAll(List<User> list) {
        SqlParameterSource[] sources = SqlParameterSourceUtils.createBatch(list); // 也可以处理List<Map>
        return namedJdbcTemplate.batchUpdate("insert into user(name, age) values(:name, :age)", sources);
    }
    
    public int deleteById(int id) {
        return jdbcTemplate.update("delete from user where id=?", id);
    }
    
    public int update(User user) {
        SqlParameterSource source = new BeanPropertySqlParameterSource(user);
        return namedJdbcTemplate.update("update user set name=:name, age=:age where id=:id", source);
    }
    
    public User getById(int id) {
        //Map<String, Object> map = jdbcTemplate.queryForMap("select * from user where id=?", id);
        return jdbcTemplate.queryForObject("select * from user where id=?", new Object[] {id}, userMapper);
    }
    
    public List<User> getAll() {
        //List<Map<String, Object>> list = jdbcTemplate.queryForList("select * from user");
        return jdbcTemplate.query("select * from user", userMapper);
    }

}
```

SimpleJdbcInsert
```java
// 使用usingGeneratedKeyColumns插入数据时会忽略id字段
SimpleJdbcInsert insert = new SimpleJdbcInsert(jdbcTemplate).withTableName("user").usingGeneratedKeyColumns("id");
// 支持SqlParameterSource与Map<String, ?>
int result = insert.execute(source);
Number key = insert.executeAndReturnKey(map);
```

SimpleJdbcCall
```java
SimpleJdbcCall call = new SimpleJdbcCall(jdbcTemplate).withProcedureName("get_user_count");
// 支持SqlParameterSource与Map<String, ?>与参数列表
Map<String, Object> out = call.execute(0);
```

自定义异常转换器
```java
jdbcTemplate.setExceptionTranslator(new SQLErrorCodeSQLExceptionTranslator(jdbcTemplate.getDataSource()) {
    @Override
    protected DataAccessException customTranslate(String task, String sql, SQLException sqlEx) {
        if (sqlEx.getErrorCode() == 1062) {
            return new DuplicateKeyException(sql, sqlEx);
        }
        return null;
    }
});
```

增加jdbc命名空间
```
xmlns:jdbc="http://www.springframework.org/schema/jdbc"
xsi:schemaLocation="http://www.springframework.org/schema/jdbc http://www.springframework.org/schema/jdbc/spring-jdbc.xsd"
```

初始化数据
```xml
<jdbc:initialize-database data-source="dataSource">
    <jdbc:script location="classpath:schema.sql" />
    <jdbc:script location="classpath:data.sql" />
</jdbc:initialize-database>
```
或使用Java配置
```java
@Bean
public DataSourceInitializer dataSourceInitializer(DataSource dataSource) {
    ResourceDatabasePopulator populator = new ResourceDatabasePopulator();
    populator.addScript(new ClassPathResource("schema.sql"));
    populator.addScript(new ClassPathResource("data.sql"));
    
    DataSourceInitializer initializer = new DataSourceInitializer();
    initializer.setDataSource(dataSource);
    initializer.setDatabasePopulator(populator);
    return initializer;
}
```
或者
```java
@Autowired
public void initializeDatabase(DataSource dataSource, @Value("classpath:schema.sql") Resource schema, @Value("classpath:data.sql") Resource data) {
    DatabasePopulatorUtils.execute(new ResourceDatabasePopulator(schema, data), dataSource);
}
```

# 事务
配置事务管理器
```xml
<bean id="transactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
    <property name="dataSource" ref="dataSource" />
</bean>
```
或使用Java配置
```java
@Bean("transactionManager")
public PlatformTransactionManager dataSourceTransactionManager(DataSource dataSource) {
    DataSourceTransactionManager transactionManager = new DataSourceTransactionManager(dataSource);
    //transactionManager.setNestedTransactionAllowed(true); // 默认为true（因事务管理器而异）
    return transactionManager;
}
```

## 编程式事务
TransactionTemplate
```xml
<bean id="transactionTemplate" class="org.springframework.transaction.support.TransactionTemplate">
    <property name="transactionManager" ref="transactionManager" />
</bean>
```
或使用Java配置
```java
@Bean
public TransactionTemplate transactionTemplate(PlatformTransactionManager transactionManager) {
    TransactionTemplate transactionTemplate = new TransactionTemplate(transactionManager);
    //transactionTemplate.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRED); // 默认
    //transactionTemplate.setIsolationLevel(TransactionDefinition.ISOLATION_DEFAULT); // 默认
    //transactionTemplate.setReadOnly(false); // 默认
    return transactionTemplate;
}
```

使用TransactionTemplate
```java
transactionTemplate.execute(new TransactionCallback<Object>() {
    @Override
    public Object doInTransaction(TransactionStatus status) {
        // 业务代码，抛出异常自动回滚
        return null;
    }
});
```

## 声明式事务
增加tx命名空间
```
xmlns:tx="http://www.springframework.org/schema/tx"
xsi:schemaLocation="http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx.xsd"
```

配置事务
```xml
<tx:advice id="txAdvice" transaction-manager="transactionManager">
    <tx:attributes>
        <tx:method name="get*" read-only="true"/>
        <tx:method name="*" propagation="NESTED"/>
    </tx:attributes>
</tx:advice>

<aop:config>
    <aop:pointcut id="txPointcut" expression="execution(* com.github.test.UserDao.*(..))"/>
    <aop:advisor advice-ref="txAdvice" pointcut-ref="txPointcut"/>
</aop:config>
```

启用注解事务
```xml
<tx:annotation-driven transaction-manager="transactionManager" />
```
或使用Java配置
```java
// 可使用@Primary或TransactionManagementConfigurer指定默认事务管理器
@EnableTransactionManagement
```

使用注解事务
```java
@Transactional
@Transactional("transactionManager")
@Transactional(propagation = Propagation.REQUIRED) // 默认
@Transactional(isolation = Isolation.DEFAULT) // 默认
@Transactional(readOnly = false) // 默认
@Transactional(rollbackFor = RuntimeException.class) // 默认
```

内部调用事务
```java
AopContext.currentProxy(); // 需打开expose-proxy
```

## 事务的传播机制
* PROPAGATION_REQUIRED：加入现有事务或新建事务
* PROPAGATION_SUPPORTS：加入现有事务或以非事务运行
* PROPAGATION_MANDATORY：加入现有事务或抛出异常
* PROPAGATION_REQUIRES_NEW：挂起当前事务并新建事务
* PROPAGATION_NOT_SUPPORTED：无视当前事务并以非事务运行
* PROPAGATION_NEVER：存在事务则抛出异常
* PROPAGATION_NESTED：新建子事务或新建事务

## UnexpectedRollbackException
加入现有事务时，父方法捕获了子方法的异常时发生
加入现有事务时，父方法子方法必须一起提交或回滚
如需实现部分提交，可使用NESTED或REQUIRES_NEW

# 嵌入式数据库
POM
```xml
<!-- H2 -->
<dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
    <version>1.4.200</version>
</dependency>
<!-- Derby -->
<dependency>
    <groupId>org.apache.derby</groupId>
    <artifactId>derby</artifactId>
    <version>10.15.2.0</version>
</dependency>
<dependency>
    <groupId>org.apache.derby</groupId>
    <artifactId>derbytools</artifactId>
    <version>10.15.2.0</version>
</dependency>
<!-- HSQLDB -->
<dependency>
    <groupId>org.hsqldb</groupId>
    <artifactId>hsqldb</artifactId>
    <version>2.5.1</version>
</dependency>
```

创建数据源
```xml
<jdbc:embedded-database id="dataSource" type="H2" generate-name="true">
    <jdbc:script location="classpath:schema.sql" />
    <jdbc:script location="classpath:data.sql" />
</jdbc:embedded-database>
```
或使用Java配置
```java
@Bean
public DataSource dataSource() {
    return new EmbeddedDatabaseBuilder()
        .setType(EmbeddedDatabaseType.H2)
        .generateUniqueName(true) // .setName("test")
        .addScripts("schema.sql", "data.sql")
        .build(); // 默认使用的用户名为sa，密码为空
}
```
或者
```java
@Bean
public DataSource dataSource() throws ClassNotFoundException {
    Class.forName("org.h2.Driver");
    // 使用文件保存数据库：jdbc:h2:file:./test
    // 使用内存数据库需设置：DB_CLOSE_DELAY=-1
    // 设置大小写敏感：DATABASE_TO_UPPER=false
    // 第一次连接时使用的用户名密码即为数据库用户名密码
    return new DriverManagerDataSource("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1");
    
    // Derby
    // org.apache.derby.jdbc.EmbeddedDriver
    // jdbc:derby:test;create=true // 基于文件
    
    // HSQLDB
    // org.hsqldb.jdbc.JDBCDriver
    // jdbc:hsqldb:mem:test;sql.syntax_mys=true // 基于内存
}
```

# Spring Boot
POM
```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-jdbc</artifactId>
</dependency>
```

## 数据源
自动配置类为`DataSourceAutoConfiguration`，默认配置类为`DataSourceProperties`
```yml
spring.datasource:
  #jndi-name: "" # 使用JNDI
  url: "jdbc:mysql://127.0.0.1:3306/test"
  username: "test"
  password: "test"
```
或使用Java配置
```java
@Bean
public DataSource dataSource() {
    return DataSourceBuilder.create()
        //.type(HikariDataSource.class)
        .url("jdbc:mysql://127.0.0.1:3306/test")
        .username("test")
        .password("test")
        .build();
}
```
```java
@Bean
@ConfigurationProperties("datasource")
// datasource.jdbc-url: jdbc:mysql://127.0.0.1:3306/test
// datasource.username: test
// datasource.password: test
public DataSource dataSource() {
    return DataSourceBuilder.create().build();
}
```
```java
@Bean
@ConfigurationProperties("datasource")
// datasource.url: jdbc:mysql://127.0.0.1:3306/test
// datasource.username: test
// datasource.password: test
public DataSourceProperties dataSourceProperties() {
    return new DataSourceProperties();
}

@Bean
public DataSource dataSource(DataSourceProperties dataSourceProperties) {
    return dataSourceProperties.initializeDataSourceBuilder().build();
}
```

### HikariCP
默认配置
```yml
spring.datasource.hikari:
  connection-timeout: 30000 # 连接超时时间
  validation-timeout: 5000 # 连接测试超时时间
  idle-timeout: 600000 # 最大空闲时间
  leak-detection-threshold: 0 # 连接泄漏超时时间
  max-lifetime: 1800000 # 最大存活时间
  maximum-pool-size: 10 # 最大连接数
  minimum-idle: 10 # 最小连接数
  connection-init-sql: "" # 连接初始化sql
  connection-test-query: "" # 连接测试sql
```

### Tomcat JDBC Connection Pool
POM
```xml
<dependency>
    <groupId>org.apache.tomcat</groupId>
    <artifactId>tomcat-jdbc</artifactId>
</dependency>
```

指定数据源类型
```yml
spring.datasource.type: org.apache.tomcat.jdbc.pool.DataSource
```

默认配置
```yml
spring.datasource.tomcat:
  init-SQL: "" # 连接初始化sql
  initial-size: 10 # 初始连接数
  max-active: 100 # 最大连接数
  max-idle: 100 # 最大空闲数
  min-idle: 10 # 最小空闲数
  max-wait: 30000 # 获取连接最大等待毫秒
  max-age: 0 # 最大存活时间
  validation-query: "" # 连接测试sql，默认自动识别
  validation-query-timeout: -1 # 连接测试超时时间
  test-on-connect: false # 建立连接时测试
  test-on-borrow: true # 获取连接时测试
  test-on-return: false # 归还连接时测试
  test-while-idle: false # 空闲时测试连接
  time-between-eviction-runs-millis: 5000 # 连接驱逐线程运行间隔
  min-evictable-idle-time-millis: 60000 # 连接保持空闲而不被驱逐的最小时间
  remove-abandoned: false # 回收泄漏连接
  remove-abandoned-timeout: 60 # 连接泄漏超时时间
  log-abandoned: false # 强制回收连接时记录日志
```

## JdbcTemplate
自动配置JdbcTemplate与NamedParameterJdbcTemplate
自动配置类为`JdbcTemplateAutoConfiguration`，默认配置类为`JdbcProperties`

自定义配置
```yml
spring.jdbc.template:
  max-rows: 100
  query-timeout: 30s
```

## 初始化数据
自动配置类为`SqlInitializationAutoConfiguration`，默认配置类为`SqlInitializationProperties`

默认配置
```yml
spring.sql.init:
  platform: "all"
  mode: EMBEDDED
```
默认在使用嵌入式数据库时初始化
1. `classpath:schema-${platform}.sql`
2. `classpath:schema.sql`
3. `classpath:data-${platform}.sql`
4. `classpath:data.sql`

自定义脚本路径
```yml
spring.sql.init:
  schema-locations: ["classpath:schema.sql"]
  data-locations: ["classpath:data.sql"]
```

## 事务管理器
自动配置类为`DataSourceTransactionManagerAutoConfiguration`

### TransactionTemplate
自动配置类为`TransactionAutoConfiguration`

### `@EnableTransactionManagement`
自动配置类为`TransactionAutoConfiguration`

默认配置
```yml
spring.aop.proxy-target-class: true
```

## 嵌入式数据库
自动配置类为`DataSourceAutoConfiguration`，默认配置类为`DataSourceProperties`

默认配置
```yml
spring.datasource:
  generate-unique-name: true
  #name: testdb
```
