### ISSUE TITLE
Spring Mail学习笔记

### ISSUE THREAD

**Issue by woshikid** [woshikid/blog#164]
POM
```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-mail</artifactId>
</dependency>
```

自动配置类为`MailSenderAutoConfiguration`，默认配置类为`MailProperties`

配置邮箱
```yml
spring:
  mail:
    host: smtp.example.com
    port: 587
    username: user@example.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true # ssl/starttls
```

JavaMailSender
```java
@Autowired
JavaMailSender mailSender;
```

发送文本邮件
```java
SimpleMailMessage message = new SimpleMailMessage();
message.setSubject("Subject");
message.setFrom("user@example.com");
message.setTo("user@example.com"); // setCc, setBcc
message.setText("Text");
mailSender.send(message);
```

发送HTML/附件
```java
MimeMessage message = mailSender.createMimeMessage();
MimeMessageHelper helper = new MimeMessageHelper(message, true);
helper.setSubject("Subject");
helper.setFrom("user@example.com");
helper.setTo("user@example.com"); // setCc, setBcc
helper.setText("Text");
//helper.setText("<img src='cid:contentId'/>", true);
helper.addAttachment("filename", new File("/path/to/file"));
//helper.addInline("contentId", new File("/path/to/file"));
mailSender.send(message);
```
