### ISSUE TITLE
Spring Cloud OpenFeign学习笔记

### ISSUE THREAD

**Issue by woshikid** [woshikid/blog#174]
POM
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-openfeign</artifactId>
</dependency>
```

启用OpenFeign
```java
@EnableFeignClients
```

默认配置
```yml
feign:
  client:
    config:
      default:
        connectTimeout: 10000 # 连接超时
        readTimeout: 60000 # 请求超时
        decode404: false # 发生404时照常解析，不抛出异常
        loggerLevel: NONE # 日志级别
  compression: # GZIP压缩
    request:
      enabled: false
      mimeTypes: text/xml, application/xml, application/json
      minRequestSize: 2048
    response:
      enabled: false
```

使用OpenFeign
```java
@FeignClient(name = "test", url = "http://localhost:8080/api") // 多个@FeignClient使用相同的名称，需要指定不同的contextId
public interface TestClient {

    @GetMapping(path = "/getUser")
    public User getUser(@RequestParam Long id); // 可使用@SpringQueryMap解析POJO或Map
    
    @PostMapping(path = "/addUser")
    // 返回为void时，decode404 = true不起作用
    public void addUser(User user); // 参数不加注解时默认为@RequestBody
    
}
```

请求降级（依赖Spring Cloud Circuit Breaker，详见 #175）
```yml
feign.circuitbreaker.enabled: true # 默认为false
```
```java
// fallback类需实现本接口并且成为bean
// 注意：由于每次都创建新的CircuitBreaker实例，因此使用Spring Retry时只降级不熔断，使用Resilience4j时可降级/熔断/限时/[隔离]
@FeignClient(name = "test", url = "http://localhost:8080/api", fallback = TestClientFallback.class)
```

请求重试/降级/熔断（依赖Spring Retry，详见 #169）
可在接口方法上使用`@Retryable`/`@Recover`/`@CircuitBreaker`以实现重试/降级/熔断

请求熔断/限流/隔离/重试/降级（依赖Resilience4j，详见 #176）
可在接口方法上使用`@CircuitBreaker`/`@RateLimiter`/`@Bulkhead`/`@Retry`以实现熔断/限流/隔离/重试/降级

使用负载均衡
```java
@FeignClient(name = "test", path = "/api") // name为springApplicationName
```

使用XML
可使用Jackson XML或JAXB，详见 #141
```java
@PostMapping(path = "/xmlTest", consumes = MediaType.APPLICATION_XML_VALUE, produces = MediaType.APPLICATION_XML_VALUE)
public User xmlTest(User user);
```

打印日志
```yml
feign:
  client:
    config:
      default: # 全局或指定feignClientName
        loggerLevel: FULL # NONE, BASIC, HEADERS, FULL

logging:
  level:
    com.github.test.TestClient: debug
```

自定义拦截器
```java
public class TestRequestInterceptor implements RequestInterceptor {

    @Override
    public void apply(RequestTemplate template) {
        template.uri("/uri", true); // append
        template.header("key", "value"); // BasicAuthRequestInterceptor
        template.query("key", "value"); // GET
        template.body("bodyText"); // POST
    }

}
```

配置拦截器
```yml
feign:
  client:
    config:
      default: # 全局或指定feignClientName
        requestInterceptors: com.github.test.TestRequestInterceptor
```
