### ISSUE TITLE
Spring Cloud Gateway学习笔记

### ISSUE THREAD

**Issue by woshikid** [woshikid/blog#180]
POM
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-gateway</artifactId>
</dependency>
```

自动配置
根据注册中心自动配置路由
```yml
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启自动配置，默认为false
          lower-case-service-id: true # 将serviceId转为小写（Eureka会将serviceId转为大写），默认为false
          url-expression: "'lb://'+serviceId" # 默认自动配置的服务地址（注意：值为SpEL表达式）
          predicates: # 自动配置的条件匹配（注意：值为SpEL表达式）（注意：自定义predicates时将覆盖默认配置）
          - Path='/'+serviceId+'/**' # 默认请求路径匹配
          filters: # 自动配置的过滤器（注意：值为SpEL表达式）（注意：自定义filters时将覆盖默认配置）
          - RewritePath='/' + serviceId + '/?(?<remaining>.*)', '/${remaining}' # 默认重写请求地址，相当于StripPrefix=1
```

自定义配置
```yml
spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000 # 连接超时，默认为45s
        response-timeout: 5s # 请求超时，默认无超时
        ssl:
          useInsecureTrustManager: true # 信任下游所有证书
          trustedX509Certificates: ["cert.pem"] # 信任下游指定证书
      default-filters: # 全局过滤器
      - RemoveResponseHeader=name # 可设置全局使用的过滤器
      routes: # 自定义路由配置
      - id: test
        order: -1 # 自定义路由默认排在自动配置的路由之后，可设为-1以提高优先级
        uri: lb://test # 指定serviceId
        #uri: http://localhost:8080 # 指定服务地址（不跟随重定向）
        #uri: forward:/test # 转发到其他地址
        predicates: # 条件匹配
        - Path=/test/**, /api/{path} # 请求路径匹配
        - After=2022-05-01T00:00:00+08:00 # 请求时间大于指定时间
        - Before=2022-10-01T00:00:00+08:00 # 请求时间小于指定时间
        - Between=2022-05-01T00:00:00+08:00, 2022-10-01T00:00:00+08:00 # 请求时间介于指定时间之间
        - Query=name, regexp # 请求参数含有指定名字的值符合指定正则表达式（值正则表达式可选）
        - Cookie=name, regexp # Cookie含有指定名字的值符合指定正则表达式
        - Header=name, regexp # Header含有指定名字的值符合指定正则表达式
        - Host=**.somehost.org, {name}.anotherhost.org # Host请求头符合指定表达式
        - Method=GET, POST # 请求符合指定动词
        - RemoteAddr=192.168.1.1/24 # IP白名单列表
        - XForwardedRemoteAddr=192.168.1.1/24 # IP白名单列表（反向代理）
        - Weight=groupName, 8 # 根据分组设置权重
        filters: # 过滤器
        - StripPrefix=1 # 转发时去掉前缀的层级，默认为0（重定向时会造成地址错误）
        - PrefixPath=/api # 转发时添加指定前缀
        - PreserveHostHeader # 转发时保留Host请求头
        - SetRequestHostHeader=localhost:8080 # 转发时设置Host请求头
        - AddRequestHeader=name, value # 转发时添加指定Header（可使用{path}{name}变量）
        - SetRequestHeader=name, value # 转发时设置指定Header（可使用{path}{name}变量）
        - MapRequestHeader=name1, name2 # 转发时将Header中name1的值添加到name2
        - RemoveRequestHeader=name # 转发时删除指定Header
        - AddRequestParameter=name, value # 转发时添加指定请求参数（可使用{path}{name}变量）
        - RemoveRequestParameter=name # 转发时删除指定请求参数
        - RewritePath=/api/(?<path>.*), /$\{path} # 重写请求地址（重定向时会造成地址错误）
        - SetPath=/{path} # 重写请求地址（可使用{path}{name}变量）
        - RequestHeaderSize=1000B # 限制Header大小，默认为16K
        - name: RequestSize # 限制请求体大小
          args:
            maxSize: 1M # 默认为5M
        - AddResponseHeader=name, value # 返回时添加指定Header（可使用{path}{name}变量）
        - SetResponseHeader=name, value # 返回时设置指定Header（可使用{path}{name}变量）
        - DedupeResponseHeader=name # 返回时去除指定Header重复值
        - RemoveResponseHeader=name # 返回时删除指定Header
        - RedirectTo=302, http://localhost:8080/api # 直接重定向到指定地址
        - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, , # 重写重定向地址（去除版本号，设置Host）
        - RewriteResponseHeader=name, regexp, replacement # 返回时替换指定Header的值
        - SetStatus=401 # 返回时设置状态码
        #- Retry=3, INTERNAL_SERVER_ERROR, GET, 5ms, 1s, 2, true
        - name: Retry # 自动重试请求（需注意与CircuitBreaker的配置顺序）
          args:
            retries: 3 # 默认为3次=初始1次+重试3次
            series: SERVER_ERROR # HttpStatus.Series，默认为SERVER_ERROR
            statuses: INTERNAL_SERVER_ERROR # HttpStatus，默认为空，与series为或的关系
            methods: GET # HttpMethod，默认为GET
            #exceptions: java.io.IOException # 默认为IOException, TimeoutException
            backoff: # 指数退让，默认无退让
              firstBackoff: 5ms # 初始退让时间，默认5ms
              maxBackoff: 1s # 最大退让时间
              factor: 2 # 退让乘数，默认为2
              basedOnPreviousValue: true # 基于前一次退让计算，默认为true
        #- CircuitBreaker=test
        - name: CircuitBreaker # 断路器（依赖Spring Cloud Circuit Breaker实现）（注意会同时使用Resilience4j的限时器）
          args:
            name: test
            fallbackUri: forward:/fallback # 只支持forward语法，可由另一个路由转发至外部
            statusCodes: [500, "NOT_FOUND"] # HttpStatus，默认为空（匹配时抛出CircuitBreakerStatusCodeException）
        metadata:
          connect-timeout: 1000 # 连接超时
          response-timeout: 5000 # 请求超时，-1为无超时
```

开启HttpClient跟随重定向
```java
@Bean
public HttpClientCustomizer httpClientCustomizer() {
    return httpClient -> httpClient.followRedirect(true);
}
```

使用CircuitBreaker（注意会同时使用Resilience4j的限时器），详见 #175, #176
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-circuitbreaker-reactor-resilience4j</artifactId>
</dependency>
```

设置CORS
```yml
spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          "[/**]":
            allowedOrigins: "https://docs.spring.io"
            allowedMethods: "*"
```

开启Reactor Netty access log
```bash
-Dreactor.netty.http.server.accessLogEnabled=true
```
```xml
<logger name="reactor.netty.http.server.AccessLog" level="INFO" additivity="false">
    <appender-ref ref="async"/>
</logger>
```

Actuator API
* GET /actuator/gateway/globalfilters
* GET /actuator/gateway/routefilters
* POST /actuator/gateway/refresh
* GET /actuator/gateway/routes
* GET /actuator/gateway/routes/{id}
* POST /actuator/gateway/routes/{id} 注意：无法修改自动配置与yml中自定义的路由
* DELETE /actuator/gateway/routes/{id} 注意：无法删除自动配置与yml中自定义的路由

GatewayFilterFactory
```java
@Component
public class TestGatewayFilterFactory extends AbstractGatewayFilterFactory<TestGatewayFilterFactory.Config> {

    public static class Config {}

    public TestGatewayFilterFactory() {
        super(Config.class);
    }

    @Override
    public GatewayFilter apply(Config config) {
        return (exchange, chain) -> {
            System.out.println(exchange.getRequest().getURI());
            ServerHttpRequest.Builder builder = exchange.getRequest().mutate();
            builder.header("key", "value");
            return chain.filter(exchange.mutate().request(builder.build()).build());
        };
    }
}
```

GlobalFilter
```java
@Component
public class TestGlobalFilter implements GlobalFilter, Ordered {

    @Override
    public int getOrder() {
        return -1;
    }

    @Override
    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
        System.out.println(exchange.getRequest().getURI());
        return chain.filter(exchange).then(Mono.fromRunnable(() -> {
            ServerHttpResponse response = exchange.getResponse();
        }));
    }
}
```

# ProxyExchange
## Spring MVC
POM
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gateway-mvc</artifactId>
</dependency>
```

反向代理
```java
@GetMapping("/test")
public ResponseEntity<?> proxy(ProxyExchange<byte[]> proxy) throws Exception {
    return proxy.uri("http://localhost:8080/test").get(); // RestTemplate(followRedirects = true)
}
```

## Webflux
POM
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gateway-webflux</artifactId>
</dependency>
```

反向代理
```java
@GetMapping("/test")
public Mono<ResponseEntity<byte[]>> proxy(ProxyExchange<byte[]> proxy) throws Exception {
    return proxy.uri("http://localhost:8080/test").get(); // WebClient(followRedirect = false)
}
```

开启WebClient跟随重定向
```java
@Bean
public WebClientCustomizer webClientCustomizer() {
    return builder -> builder.clientConnector(new ReactorClientHttpConnector(HttpClient.create().followRedirect(true)));
}
```
