### ISSUE TITLE
Spring Cloud Config学习笔记

### ISSUE THREAD

**Issue by woshikid** [woshikid/blog#184]
# Spring Cloud Config Server
POM
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-config-server</artifactId>
</dependency>
```

自定义配置
```yml
spring:
  cloud:
    config:
      server:
        git: # 使用git管理配置文件（默认）
          uri: https://github.com/username/config.git # clone到temp目录
          default-label: master # 默认git分支，默认为main
          search-paths: ["/**"] # 配置文件路径，默认不搜索子目录
          #username: username
          #password: password
          #passphrase: passphrase # 私钥密码
          refresh-rate: 0 # 默认为0，请求时才刷新
          force-pull: true # 忽略本地修改，默认为false
        native: # 本地配置文件
          search-locations: file:///path/to/config # 默认为[classpath:/,classpath:/config/,file:./,file:./config/]
          default-label: master # 对应路径为{search-locations}/{label}，默认为master
  #profiles.active: native # 使用本地配置文件，默认使用git
```

使用Config Server
```java
@EnableConfigServer
```

访问配置
```
http://localhost:8080/{springApplicationName}/{profile}[/{branch}]
http://localhost:8080/{springApplicationName}-{profile}.yml|properties|json
http://localhost:8080/{branch}/{springApplicationName}-{profile}.yml|properties|json # 有bug
http://localhost:8080/{springApplicationName}/{profile}/{branch}/path/to/any/file
```

## JDBC
POM
```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-jdbc</artifactId>
</dependency>
```

自定义配置
```yml
spring:
  profiles:
    active: jdbc # 使用JDBC配置，默认使用git
#  cloud:
#    config:
#      server:
#        jdbc:
#          sql: SELECT KEY, VALUE from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=? # 默认sql
```

配置表
```sql
CREATE TABLE PROPERTIES (
  APPLICATION varchar(20) NOT NULL,
  PROFILE varchar(20) NULL,
  LABEL varchar(20) NOT NULL DEFAULT 'master',
  KEY varchar(100) NOT NULL,
  VALUE varchar(200) NOT NULL
);
```

# Spring Cloud Config Client
POM
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-config</artifactId>
</dependency>
```

## 使用import的方式启动
自定义配置
```yml
spring:
  config:
    import: "optional:configserver:http://localhost:8080"
    #import: "optional:configserver:" # 使用spring.cloud.config.uri或自动获取
  cloud:
    config:
      #uri: http://localhost:8080 # 优先级低于spring.config.import
      label: master # git分支，默认为空
      name: test # 默认为spring.application.name
      profile: default # 默认为default则使用spring.profiles.active或default
      #discovery:
        #enabled: true # 自动获取配置服务（依赖注册中心），默认为false
        #service-id: config # 默认为configserver
```

配置优先级
路径优先级与`classpath:/`同级
```
1. configserver:{springApplicationName}-{profile}.yml
2. configserver:application-{profile}.yml # 全局配置
3. classpath:/application-{profile}.yml
4. configserver:{springApplicationName}.yml
5. configserver:application.yml # 全局配置
6. classpath:/application.yml
```

## 使用bootstrap的方式启动
```bash
-Dspring.cloud.bootstrap.enabled=true
```
或引入POM
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-bootstrap</artifactId>
</dependency>
```

自定义配置（bootstrap.yml）
```yml
spring:
  cloud:
    config:
      uri: http://localhost:8080 # 默认为http://localhost:8888
      fail-fast: true # 相当于去掉import的optional，默认为false
      name: test # 或将spring.application.name定义在bootstrap.yml中
      #discovery:
        #enabled: true # 自动获取配置服务（依赖注册中心），默认为false
        #service-id: config # 默认为configserver
  profiles:
    active: dev # 需定义在bootstrap.yml中
# 注册中心相关配置也需定义在bootstrap.yml中
```

配置优先级
**高于所有配置，甚至高于测试参数**
```
1. configserver:{springApplicationName}-{profile}.yml
2. configserver:application-{profile}.yml # 全局配置
3. configserver:{springApplicationName}.yml
4. configserver:application.yml # 全局配置
```

## 手动刷新配置
手动刷新
```bash
curl -X POST http://clientIP:8080/actuator/refresh
```

标记bean需要重新加载配置
```java
@RefreshScope
```

### Spring Cloud Bus（详见 #186）
刷新所有配置
```bash
curl -X POST http://localhost:8080/actuator/busrefresh
```

### Spring Cloud Config Monitor（依赖Spring Cloud Bus）
POM（Spring Cloud Config Server）
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-config-monitor</artifactId>
</dependency>
```

webhook
支持Github, Gitlab, Gitea, Gitee, Gogs, Bitbucket或本地配置文件
```
http://serverIP:8080/monitor
```
自动根据修改的文件名判断应用名，如修改foo.properties则更新foo应用
注意：目前由于bug而不支持带profile的文件，如foo-dev.properties
