### ISSUE TITLE
Spring Cloud Bus学习笔记

### ISSUE THREAD

**Issue by woshikid** [woshikid/blog#186]
POM
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-bus-amqp</artifactId>
</dependency>
```

RabbitMQ配置，详见 #185
```yml
spring:
  rabbitmq:
    host: localhost # 默认为localhost
    port: 5672 # 默认为5672或5671(SSL)
    username: guest # 默认为guest
    password: password # 默认为guest
```

刷新配置
```bash
curl -X POST http://localhost:8080/actuator/busrefresh
```

更新配置
```bash
curl -X POST -H "Content-Type: application/json" -d '{"name":"key","value":"value"}' http://localhost:8080/actuator/busenv
```
