### ISSUE TITLE
Consul学习笔记

### ISSUE THREAD

**Issue by woshikid** [woshikid/blog#187]
# 安装Consul
CentOS
```bash
sudo yum install yum-utils # 安装yum-config-manager
sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo # 添加HashiCorp源
sudo yum install consul # 安装Consul
```

Ubuntu
```bash
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add - # 添加HashiCorp GPG证书
sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" # 添加HashiCorp源
sudo apt-get install consul # 安装Consul
```

Windows
```
https://www.consul.io/downloads
```

启动Consul
```bash
consul agent -dev # 开发模式
consul agent [-ui] [-server] [-bind=192.168.1.1] [-client=0.0.0.0] [-node=node1] -data-dir=/tmp/consul # 启动节点，默认为client模式，client参数表示客户端白名单
consul agent -server -bootstrap [-bootstrap-expect=1] -data-dir=/tmp/consul # 首次启动集群必须使用bootstrap或bootstrap-expect模式
```

加入/离开集群
```bash
consul join 192.168.1.1
consul leave
consul force-leave node1
```

查看集群成员/状态
```bash
consul members [-detailed]
consul catalog datacenters
consul catalog nodes [-service=test] [-detailed]
consul catalog services [-node=node1] [-tags]
```

注册/注销服务
```bash
consul services register [-id=test-8080] -name=test [-address=192.168.1.1] -port=8080 [-tag=web] [-meta="secure=true"] # secure表示是否为https
consul services deregister -id=test-8080
```

Key/Value操作
```bash
consul kv put [-flags=42] dir/key value
consul kv get [-detailed] [-recurse] dir/key
consul kv delete [-recurse] dir/key
```

管理界面
http://localhost:8500

# 注册中心
POM
```xml
<!-- 默认已包含Spring Cloud LoadBalancer -->
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-consul-discovery</artifactId>
</dependency>
```

自定义配置
```yml
spring:
  cloud:
    consul:
      host: localhost # 默认为localhost
      port: 8500 # 默认为8500
      discovery:
        service-name: test # 默认为spring.application.name
        hostname: localhost # 默认自动获取
        #prefer-ip-address: true # 使用IP而不是hostname
        #instance-id: ${spring.application.name}-${spring.application.instance_id:${server.port:8080}}
        health-check-path: /actuator/health # 健康检查地址（默认值）
        health-check-interval: 10s # 健康检查间隔（默认值）
        #scheme: https # 注册为https服务
```

使用DiscoveryClient
```java
@Autowired
private DiscoveryClient discoveryClient;

List<ServiceInstance> serviceInstances = discoveryClient.getInstances(springApplicationName);
String url = serviceInstances.get(0).getUri().toString();
```

# 配置中心
POM
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-consul-config</artifactId>
</dependency>
```

创建配置信息
http://localhost:8500/ui/dc1/kv/create
```bash
consul kv put config/test/data "info.app.name: testApp"
# profile配置
consul kv put config/test,dev/data "info.app.name: testApp"
# 全局配置
consul kv put config/application/data "info.app.name: testApp"
```

## 使用import的方式启动
自定义配置
```yml
spring:
  config:
    import: "optional:consul:localhost:8500"
    #import: "optional:consul:" # 使用spring.cloud.consul.host/port
    #import: "optional:consul:localhost:8500/path/to/test;/path/to/test-dev" # 仅从指定路径获取配置（路径不支持逗号）
  cloud:
    consul:
      #host: localhost # 优先级低于spring.config.import
      #port: 8500 # 优先级低于spring.config.import
      config:
        prefixes: config # 默认配置路径为/config
        name: test # 默认为spring.application.name
        default-context: application # 全局配置名，默认为application
        profile-separator: "," # profile分隔符（默认值）
        data-key: data # 配置名，默认为data
        format: yaml # 默认为key-value
```

配置优先级
路径优先级与`classpath:/`同级
```
1. consul:config/{springApplicationName},{profile}/data
2. consul:config/application,{profile}/data # 全局配置
3. classpath:/application-{profile}.yml
4. consul:config/{springApplicationName}/data
5. consul:config/application/data # 全局配置
6. classpath:/application.yml
```

## 使用bootstrap的方式启动
```bash
-Dspring.cloud.bootstrap.enabled=true
```
或引入POM
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-bootstrap</artifactId>
</dependency>
```

自定义配置（bootstrap.yml）
```yml
spring:
  cloud:
    consul:
      host: localhost # 默认为localhost
      port: 8500 # 默认为8500
      config:
        fail-fast: true # 相当于去掉import的optional，默认为true
        name: test # 或将spring.application.name定义在bootstrap.yml中
```

配置优先级
**高于所有配置，甚至高于测试参数**
```
1. consul:config/{springApplicationName},{profile}/data
2. consul:config/{springApplicationName}/data
3. consul:config/application,{profile}/data # 全局配置
4. consul:config/application/data # 全局配置
```

## 刷新配置
当Consul中的配置信息变更时将自动刷新配置

手动刷新
```bash
curl -X POST http://localhost:8080/actuator/refresh
```

标记bean需要重新加载配置
```java
@RefreshScope
```
