### ISSUE TITLE
Druid基本配置

### ISSUE THREAD

**Issue by woshikid** [woshikid/blog#41]
# POM
```xml
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>druid</artifactId>
    <version>1.2.5</version>
</dependency>
```

# 配置bean
````xml
<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">
    <!-- 默认根据url自动识别 -->
    <property name="driverClassName" value="com.mysql.cj.jdbc.Driver" />
    <property name="url" value="jdbc:mysql://127.0.0.1:3306/test" />
    <property name="username" value="test" />
    <property name="password" value="test" />
    <!-- 初始连接数，默认为0 -->
    <property name="initialSize" value="1" />
    <!-- 最小连接数，默认为0 -->
    <property name="minIdle" value="1" />
    <!-- 最大连接数，默认为8 -->
    <property name="maxActive" value="100" />
    <!-- 获取连接最大等待毫秒，默认为-1 -->
    <property name="maxWait" value="10000" />
    <!-- 连接测试sql，默认为空 -->
    <property name="validationQuery" value="select 1" />
    <!-- 获取连接时测试，默认为false -->
    <property name="testOnBorrow" value="false" />
    <!-- 归还连接时测试，默认为false -->
    <property name="testOnReturn" value="false" />
    <!-- 获取连接时空闲时间大于timeBetweenEvictionRunsMillis时检测，默认为true -->
    <property name="testWhileIdle" value="true" />
    <!-- 连接驱逐线程运行间隔，默认为60秒 -->
    <property name="timeBetweenEvictionRunsMillis" value="60000" />
    <!-- 连接保持空闲而不被驱逐的最小时间，默认为1800秒 -->
    <property name="minEvictableIdleTimeMillis" value="1800000" />
    <!-- 连接泄漏强制回收，默认为false -->
    <property name="removeAbandoned" value="true" />
    <!-- 连接泄漏超时时间，默认为300秒 -->
    <property name="removeAbandonedTimeout" value="1800" />
    <!-- 强制回收连接时记录日志，默认为false -->
    <property name="logAbandoned" value="true" />
    <!-- 扩展插件 -->
    <!-- 日志支持log4j, log4j2, slf4j, commonLogging -->
    <!-- <property name="filters" value="mergeStat,wall,slf4j" /> -->
    <property name="proxyFilters">
        <list>
            <!-- SQL监控 -->
            <bean class="com.alibaba.druid.filter.stat.MergeStatFilter">
                <!-- 慢sql执行时间，默认为3秒 -->
                <property name="slowSqlMillis" value="3000" />
                <!-- 日志记录慢sql，默认为false -->
                <property name="logSlowSql" value="true" />
            </bean>
            <!-- SQL防火墙 -->
            <bean class="com.alibaba.druid.wall.WallFilter">
                <!-- 日志记录SQL攻击，默认为false -->
                <property name="logViolation" value="false" />
                <!-- SQL攻击抛出异常，默认为true -->
                <property name="throwException" value="true" />
                <!-- 拦截配置默认值 -->
                <property name="config">
                    <bean class="com.alibaba.druid.wall.WallConfig">
                        <property name="selelctAllow" value="true" />
                        <property name="selectAllColumnAllow" value="true" />
                        <property name="selectIntoAllow" value="true" />
                        <property name="deleteAllow" value="true" />
                        <property name="updateAllow" value="true" />
                        <property name="insertAllow" value="true" />
                        <property name="replaceAllow" value="true" />
                        <property name="mergeAllow" value="true" />
                        <property name="callAllow" value="true" />
                        <property name="truncateAllow" value="true" />
                        <property name="createTableAllow" value="true" />
                        <property name="alterTableAllow" value="true" />
                        <property name="dropTableAllow" value="true" />
                        <property name="commentAllow" value="false" />
                        <property name="noneBaseStatementAllow" value="false" />
                        <property name="multiStatementAllow" value="false" />
                        <property name="commitAllow" value="true" />
                        <property name="rollbackAllow" value="true" />
                        <property name="selectWhereAlwayTrueCheck" value="true" />
                        <property name="deleteWhereAlwayTrueCheck" value="true" />
                        <property name="deleteWhereNoneCheck" value="false" />
                        <property name="updateWhereAlayTrueCheck" value="true" />
                        <property name="updateWhereNoneCheck" value="false" />
                        <property name="conditionAndAlwayTrueAllow" value="false" />
                        <property name="conditionAndAlwayFalseAllow" value="false" />
                        <property name="mustParameterized" value="false" />
                        <property name="selectLimit" value="-1" />
                    </bean>
                </property>
            </bean>
            <!-- SQL日志输出 -->
            <!-- 日志支持Log4jFilter, Log4j2Filter, Slf4jLogFilter, CommonsLogFilter -->
            <!-- 在日志框架中按需开启四种Logger -->
            <!-- <logger name="druid.sql.DataSource" level="DEBUG"> -->
            <!-- <logger name="druid.sql.Connection" level="DEBUG"> -->
            <!-- <logger name="druid.sql.Statement" level="DEBUG"> -->
            <!-- <logger name="druid.sql.ResultSet" level="DEBUG"> -->
            <bean class="com.alibaba.druid.filter.logging.Slf4jLogFilter">
                <!-- 输出可执行的SQL -->
                <property name="statementExecutableSqlLogEnable" value="true" />
                <!-- 简化输出内容 -->
                <property name="statementCreateAfterLogEnabled" value="false" />
                <property name="statementPrepareAfterLogEnabled" value="false" />
                <property name="statementExecuteQueryAfterLogEnabled" value="false" />
                <property name="statementExecuteUpdateAfterLogEnabled" value="false" />
                <property name="statementCloseAfterLogEnabled" value="false" />
                <property name="statementParameterSetLogEnabled" value="false" />
            </bean>
        </list>
    </property>
</bean>
````

# 配置JNDI
````xml
<Resource name="jdbc/TestDB" auth="Container" type="javax.sql.DataSource"
    factory="com.alibaba.druid.pool.DruidDataSourceFactory"
    driverClassName="com.mysql.cj.jdbc.Driver"
    url="jdbc:mysql://127.0.0.1:3306/test" username="test" password="test"
    initialSize="1" minIdle="1" maxActive="100" maxWait="10000" validationQuery="select 1"
    removeAbandoned="true" removeAbandonedTimeout="1800" logAbandoned="true"
    filters="mergeStat,wall,slf4j"
    connectionProperties="druid.stat.slowSqlMillis=3000;druid.stat.logSlowSql=true;druid.log.stmt.executableSql=true" />
````

# 配置监控页面
````xml
<servlet>
    <servlet-name>druidStatView</servlet-name>
    <servlet-class>com.alibaba.druid.support.http.StatViewServlet</servlet-class>
    <init-param>
        <!-- 访问控制白名单 -->
        <param-name>allow</param-name>
        <param-value>127.0.0.1/24</param-value>
    </init-param>
    <init-param>
        <!-- 允许清空统计数据 -->
        <param-name>resetEnable</param-name>
        <param-value>true</param-value>
    </init-param>
    <init-param>
        <param-name>loginUsername</param-name>
        <param-value>admin</param-value>
    </init-param>
    <init-param>
        <param-name>loginPassword</param-name>
        <param-value>admin</param-value>
    </init-param>
</servlet>
<servlet-mapping>
    <servlet-name>druidStatView</servlet-name>
    <url-pattern>/druid/*</url-pattern>
</servlet-mapping>
````

# 配置web统计
````xml
<filter>
    <filter-name>druidWebStatFilter</filter-name>
    <filter-class>com.alibaba.druid.support.http.WebStatFilter</filter-class>
    <init-param>
        <!-- 排除统计的url -->
        <param-name>exclusions</param-name>
        <param-value>*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*</param-value>
    </init-param>
    <init-param>
        <!-- 开启session统计，默认为true -->
        <param-name>sessionStatEnable</param-name>
        <param-value>true</param-value>
    </init-param>
    <init-param>
        <!-- 最大统计session数，默认为1000 -->
        <param-name>sessionStatMaxCount</param-name>
        <param-value>1000</param-value>
    </init-param>
    <init-param>
        <!-- 从session中获取用户名 -->
        <param-name>principalSessionName</param-name>
        <param-value>xxx.user</param-value>
    </init-param>
    <init-param>
        <!-- 从cookie中获取用户名 -->
        <param-name>principalCookieName</param-name>
        <param-value>xxx.user</param-value>
    </init-param>
    <init-param>
        <!-- 监控单个url调用的sql列表，默认为false -->
        <param-name>profileEnable</param-name>
        <param-value>true</param-value>
    </init-param>
</filter>
<filter-mapping>
    <filter-name>druidWebStatFilter</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>
````

# 配置bean统计
## bean
````xml
<bean id="druidStatInterceptor" class="com.alibaba.druid.support.spring.stat.DruidStatInterceptor" />
````

## 代理
````xml
<aop:config proxy-target-class="true">
    <aop:pointcut id="druidStatPointcut" expression="execution(* com.mycompany.dao.*.*(..))" />
    <aop:advisor advice-ref="druidStatInterceptor" pointcut-ref="druidStatPointcut" />
</aop:config>
````
或
````xml
<bean class="com.alibaba.druid.support.spring.stat.BeanTypeAutoProxyCreator">
    <property name="targetBeanType" value="xxxx.ABCInterface" />
    <property name="interceptorNames">
        <list>
            <value>druidStatInterceptor</value>
        </list>
    </property>
</bean>
````
或
````xml
<bean class="org.springframework.aop.framework.autoproxy.BeanNameAutoProxyCreator">
    <property name="proxyTargetClass" value="true" />
    <property name="beanNames">
        <list>
            <value>xxx-dao</value>
            <value>xxx-service</value>
        </list>
    </property>
    <property name="interceptorNames">
        <list>
            <value>druidStatInterceptor</value>
        </list>
    </property>
</bean>
````
或
````xml
<bean id="druidStatPointcut" class="org.springframework.aop.support.JdkRegexpMethodPointcut" scope="prototype">
    <property name="patterns">
        <list>
            <value>com.mycompany.service.*</value>
            <value>com.mycompany.dao.*</value>
        </list>
    </property>
</bean>

<aop:config proxy-target-class="true">
    <aop:advisor advice-ref="druidStatInterceptor" pointcut-ref="druidStatPointcut" />
</aop:config>
````

# 数据库密码加密
## 密码加密
````shell
java -cp druid-1.2.5.jar com.alibaba.druid.filter.config.ConfigTools you_password
````

## 密码解密
````xml
<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">
    ...
    <property name="password" value="${password}" />
    <property name="filters" value="config" />
    <property name="connectionProperties" value="config.decrypt=true;config.decrypt.key=${publickey}" />
</bean>
````

# 远程配置文件
````xml
<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">
    <property name="filters" value="config" />
    <property name="connectionProperties" value="config.file=file:///home/admin/druid-pool.properties" />
</bean>
````
支持从http远程获取config.file=http://127.0.0.1/druid-pool.properties

# Spring Boot
POM
```xml
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>druid-spring-boot-starter</artifactId>
    <version>1.2.6</version>
</dependency>
```

自动配置类为`DruidDataSourceAutoConfigure`，默认配置类为`DruidStatProperties`

默认数据源配置
```yml
spring.datasource.druid:
  connection-init-sqls: "" # 连接初始化sql
  initial-size: 0 # 初始连接数
  min-idle: 0 # 最小连接数
  max-active: 8 # 最大连接数
  max-wait: -1 # 获取连接最大等待毫秒
  #validation-query: "" # 连接测试sql
  validation-query-timeout: -1 # 连接测试超时时间
  test-on-borrow: false # 获取连接时测试
  test-on-return: false # 归还连接时测试
  test-while-idle: true # 获取连接时空闲时间大于timeBetweenEvictionRunsMillis时检测
  time-between-eviction-runs-millis: 60000 # 连接驱逐线程运行间隔
  min-evictable-idle-time-millis: 1800000 # 连接保持空闲而不被驱逐的最小时间
  max-evictable-idle-time-millis: 25200000 # 最大存活时间
  remove-abandoned: false # 连接泄漏强制回收
  remove-abandoned-timeout: 300 # 连接泄漏超时时间
  log-abandoned: false # 强制回收连接时记录日志
  filters: "" # 扩展插件: "mergeStat,wall,slf4j"
```

或使用Java配置
```java
@Bean
@ConfigurationProperties("spring.datasource.druid")
public DataSource dataSource() {
    return DruidDataSourceBuilder.create().build();
}
```

默认监控/统计配置
```yml
spring.datasource.druid:
  stat-view-servlet: # 监控页面
    enabled: false
    url-pattern: "/druid/*"
    allow: "127.0.0.1"
    deny: ""
    login-username: ""
    login-password: ""
    reset-enable: false
  web-stat-filter: # web统计
    enabled: false
    url-pattern: "/*"
    exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
    session-stat-enable: true
    session-stat-max-count: 1000
    principal-session-name: ""
    principal-cookie-name: ""
    profile-enable: false
  #aop-patterns: "" # bean统计，需依赖Spring AOP/AspectJ
```

默认Filter配置
```yml
spring.datasource.druid.filter:
  stat: # SQL监控
    enabled: false
    slow-sql-millis: 3000
    log-slow-sql: false
    merge-sql: false
  wall: # SQL防火墙
    enabled: false
    log-violation: false
    throw-exception: true
    config: # 拦截配置
      comment-allow: false
      multi-statement-allow: false
      condition-and-alway-true-allow: false
      condition-and-alway-false-allow: false
      select-limit: -1
  slf4j: # SQL日志输出
    enabled: false
    statement-executable-sql-log-enable: false
```

获取监控数据
```java
List<Map<String, Object>> dataSourceStat = DruidStatManagerFacade.getInstance().getDataSourceStatDataList(); // 数据源信息
List<List<String>> activeConnStackTrace = DruidStatManagerFacade.getInstance().getActiveConnStackTraceList(); // 活动连接堆栈
List<Map<String, Object>> webAppStat = WebAppStatManager.getInstance().getWebAppStatData(); // web统计信息
List<Map<String, Object>> uriStat = WebAppStatManager.getInstance().getURIStatData(); // URI监控信息
List<Map<String, Object>> sessionStat = WebAppStatManager.getInstance().getSessionStatData(); // Session监控信息
List<Map<String, Object>> springStat = SpringStatManager.getInstance().getMethodStatData(); // Spring监控信息
```

数据库密码加密
```yml
spring.datasource.druid.filter.config.enabled: true
spring.datasource.druid.connection-properties: "config.decrypt=true;config.decrypt.key=${publickey}"
```
