### ISSUE TITLE
Kibana学习笔记

### ISSUE THREAD

**Issue by woshikid** [woshikid/blog#46]
# 安装/运行
```bash
curl -L -O https://artifacts.elastic.co/downloads/kibana/kibana-7.4.2-linux-x86_64.tar.gz
tar xzvf kibana-7.4.2-linux-x86_64.tar.gz
cd kibana-7.4.2-linux-x86_64/
./bin/kibana --host 0.0.0.0
```

验证运行
http://127.0.0.1:5601/

# 配置
vi config/kibana.yml
```yml
elasticsearch.hosts: ["http://localhost:9200"]
server.host: "0.0.0.0"
#elasticsearch.username: "kibana"
#elasticsearch.password: "pass"
```

使用高德地图
vi config/kibana.yml
```yml
map.tilemap.url: 'http://webrd02.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=7&x={x}&y={y}&z={z}'
```

设置请求超时
vi config/kibana.yml
```yml
elasticsearch.requestTimeout: 300000
```
