### ISSUE TITLE
Filebeat学习笔记

### ISSUE THREAD

**Issue by woshikid** [woshikid/blog#91]
# 安装/启动
```bash
curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.2-linux-x86_64.tar.gz
tar xzvf filebeat-7.4.2-linux-x86_64.tar.gz
cd filebeat-7.4.2-linux-x86_64
./filebeat -e
```

# 配置
vi filebeat.yml
```yml
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
  #fields_under_root: true
  #fields:
    #type: apache
  #multiline.pattern: '^\['
  #multiline.negate: true
  #multiline.match: after
  #multiline.timeout: 10s

filebeat.config.modules:
  reload.enabled: true

output.elasticsearch:
  hosts: ["myEShost:9200"]
  #username: "elastic"
  #password: "elastic"

output.logstash:
  hosts: ["mylogstashhost1:5044", "mylogstashhost2:5044"]
  loadbalance: true

setup.kibana:
  host: "mykibanahost:5601"
```

## 手工加载index template
```bash
./filebeat setup --index-management -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["localhost:9200"]'
```

## 加载Kibana dashboards
```bash
./filebeat setup --dashboards
```

## 安装通用日志模块
```bash
./filebeat modules list
./filebeat modules enable apache elasticsearch logstash kibana
```

### 初始化环境
```bash
./filebeat setup -e
```

### apache
vi modules.d/apache.yml
```yml
- module: apache
  access:
    enabled: true
    var.paths: ["/path/to/log/apache/access.log*"]

  error:
    enabled: true
    var.paths: ["/path/to/log/apache/error.log*"]
```

### elasticsearch
vi modules.d/elasticsearch.yml
```yml
- module: elasticsearch
  server:
    enabled: true
    var.paths: ["/path/to/log/elasticsearch/*_server.json"]

  gc:
    enabled: true
    var.paths: ["/path/to/log/elasticsearch/gc.log*"]

  audit:
    enabled: true
    var.paths: ["/path/to/log/elasticsearch/*_audit.json"]

  slowlog:
    enabled: true
    var.paths: ["/path/to/log/elasticsearch/*_slowlog.json"]

  deprecation:
    enabled: true
    var.paths: ["/path/to/log/elasticsearch/*_deprecation.json"]
```

### logstash
vi modules.d/logstash.yml
```yml
- module: logstash
  log:
    enabled: true
    var.paths: ["/path/to/log/logstash/logstash-plain.log"]

  slowlog:
    enabled: true
    var.paths: ["/path/to/log/logstash/logstash-slowlog-plain.log"]
```

### kibana
```yml
- module: kibana
  log:
    enabled: true
    var.paths: ["/path/to/log/kibana/nohup.log"]
```

## 手工加载pipelines
```bash
./filebeat setup --pipelines --modules apache elasticsearch logstash kibana
```

# 文件位置记录
filebeat会记录文件读取位置
```
data/registry/filebeat/data.json
```
删除文件即可重新读取日志文件
