### ISSUE TITLE
Metricbeat学习笔记

### ISSUE THREAD

**Issue by woshikid** [woshikid/blog#92]
# 安装/启动
```bash
curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.2-linux-x86_64.tar.gz
tar xzvf metricbeat-7.4.2-linux-x86_64.tar.gz
cd metricbeat-7.4.2-linux-x86_64
./metricbeat -e
```

# 配置
vi metricbeat.yml
```yml
metricbeat.config.modules:
  reload.enabled: true

setup.kibana:
  host: "mykibanahost:5601"

output.elasticsearch:
  hosts: ["myEShost:9200"]
  #username: "elastic"
  #password: "elastic"

output.logstash:
  hosts: ["mylogstashhost1:5044", "mylogstashhost2:5044"]
  loadbalance: true
```

## 手工加载index template
```bash
./metricbeat setup --index-management -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["localhost:9200"]'
```

## 加载Kibana dashboards
```bash
./metricbeat setup --dashboards
```

## 安装通用监测模块
```bash
./metricbeat modules list
./metricbeat modules enable apache elasticsearch logstash kibana
```

### 初始化环境
```bash
./metricbeat setup -e
```

### apache
vi modules.d/apache.yml
```yml
- module: apache
  metricsets:
    - status
  period: 10s
  hosts: ["http://127.0.0.1"]
  #server_status_path: "server-status"
  #username: "username"
  #password: "password"
```

### elasticsearch
vi modules.d/elasticsearch.yml
```yml
- module: elasticsearch
  metricsets:
    - node
    - node_stats
    #- cluster_stats
    #- index
    #- shard
  period: 10s
  hosts: ["http://localhost:9200"]
  #username: "elastic"
  #password: "elastic"
```

### logstash
vi modules.d/logstash.yml
```yml
- module: logstash
  metricsets:
    - node
    - node_stats
  period: 10s
  hosts: ["localhost:9600"]
```

### kibana
vi modules.d/kibana.yml
```yml
- module: kibana
  metricsets:
    - status
  period: 10s
  hosts: ["localhost:5601"]
  #basepath: ""
  #username: "kibana"
  #password: "kibana"
```
