### ISSUE TITLE
Heartbeat学习笔记

### ISSUE THREAD

**Issue by woshikid** [woshikid/blog#93]
# 安装/启动
```bash
curl -L -O https://artifacts.elastic.co/downloads/beats/heartbeat/heartbeat-7.4.2-linux-x86_64.tar.gz
tar xzvf heartbeat-7.4.2-linux-x86_64.tar.gz
cd heartbeat-7.4.2-linux-x86_64
./heartbeat -e
```

# 配置
vi heartbeat.yml
```yml
heartbeat.config.monitors:
  reload.enabled: true

heartbeat.monitors:
#- type: http
  #urls: ["http://localhost:9200"]
  #schedule: '@every 10s'

output.elasticsearch:
  hosts: ["myEShost:9200"]
  #username: "elastic"
  #password: "elastic"

output.logstash:
  hosts: ["mylogstashhost1:5044", "mylogstashhost2:5044"]
  loadbalance: true

setup.kibana:
  host: "mykibanahost:5601"
```

## http心跳
vi monitors.d/http.yml
```yml
- type: http
  name: http-localhost
  #enabled: true

  schedule: '@every 5s'
  urls: ["http://localhost:9200"]

  #proxy_url: ''
  #timeout: 16s

  #username: 'elastic'
  #password: 'elastic'

  #check.request:
    #method: "GET"
    #headers:
    #body:

  #check.response:
    #status: 200
    #headers:
    #body: 'regular expressions' # positive子元素之间是或关系，negative子元素之间是与关系
    #json:
      #- description: Explanation of what the check does
        #condition:
          #equals:
            #myField: expectedValue

  #ipv4: true
  #ipv6: true
  #mode: all
```

## tcp心跳
vi monitors.d/tcp.yml
```yml
- type: tcp
  name: tcp-localhost
  #enabled: true

  schedule: '@every 5s'
  hosts: ["localhost:9200"]
  #ports: [80, 9200, 5044]

  #proxy_url: ''
  #timeout: 16s

  #check:
    #send: ''
    #receive: ''

  #ipv4: true
  #ipv6: true
  #mode: all
```

## icmp心跳 (requires root)
```shell
sudo chown root heartbeat.yml
sudo chown root monitors.d/icmp.yml
sudo ./heartbeat -e
```

vi monitors.d/icmp.yml
```yml
- type: icmp
  name: icmp-localhost
  #enabled: true

  schedule: '*/5 * * * * * *'
  hosts: ["localhost"]

  timeout: 16s
  wait: 1s

  #ipv4: true
  #ipv6: true
  #mode: all
```

## 手工加载index template
```
./heartbeat setup --index-management -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["localhost:9200"]'
```
